# docker-compose build
version: "3"

volumes:
  data:
    driver: local
  backup:
    driver: local

networks:
  default:
    driver: bridge

services:
  db:
    image: kartoza/postgis
    container_name: postgis
    hostname: postgis
    volumes:
      - data:/var/lib/postgresql
      - backup:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - LANG=${LANG:-cs_CZ.UTF-8}
      - LANGUAGE=${LANGUAGE:-cs_CZ:cs}
      - LC_ALL=${LC_ALL:-cs_CZ.UTF-8}
      - LC_COLLATE=${LC_COLLATE:-cs_CZ.UTF-8}
      - DEFAULT_COLLATION=${DEFAULT_COLLATION:-cs_CZ.UTF-8}
      - DEFAULT_CTYPE:=${DEFAULT_COLLATION:-cs_CZ.UTF-8}
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
      - TZ=Europe/Prague
    ports:
      - 25432:5432
    restart: always
    networks:
      default:
        aliases:
          - db
          - pg
          - database
          - sql
          - postgis
    healthcheck:
      test: "exit 0"

  backup:
    image: kartoza/pg-backup
    container_name: postgis-backup
    hostname: postgis-backup
    volumes:
      - backup:/backups
    links:
      - db:db
    environment:
      # List databases to back up; defaults to all
      - "DBLIST=gis"
      # Remove backups older than (in days)
      - DUMPPREFIX=PG_db
      - REMOVE_BEFORE=30
      - POSTGRES_HOST=postgis
      - POSTGRES_DBNAME=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
      # For restore script
      - TARGET_DB=gis
      - WITH_POSTGIS=1
      - TARGET_ARCHIVE=/backups/target_archive.dmp
      - TZ=Europe/Prague
    restart: always
    networks:
      default:
        aliases:
          - backup
          - pg-backup
          - postgis-backup
          - db-backup
          - sql-backup
    depends_on:
      - db
