version: "3"

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local

services:
  db:
    image: library/mariadb
    container_name: ca_db
    environment:
      MYSQL_ROOT_PASSWORD: foo123
      MYSQL_DATABASE: ejbca
      MYSQL_USER: ejbca
      MYSQL_PASSWORD: ejbca
      LANG: C.UTF_8  # this one should be added
      TZ: Europe/Prague
    restart: always
    volumes:
      - data:/var/lib/mysql"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    networks:
      default:
        aliases:
          - db
          - ejbca-database
          - mysql
          - mariadb
  ca1:
    image: primekey/ejbca-ce
    container_name: ca1
    environment:
      DATABASE_JDBC_URL: jdbc:mysql://db:3306/ejbca?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      PROXY_AJP_BIND: 0.0.0.0
      TZ: Europe/Prague
    restart: always
    depends_on:
      - db
    networks:
      default:
        aliases:
          - ca1
          - ejbca1
          - node1
  ca2:
    image: primekey/ejbca-ce
    container_name: ca2
    environment:
      DATABASE_JDBC_URL: jdbc:mysql://db:3306/ejbca?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      PROXY_AJP_BIND: 0.0.0.0
      TZ: Europe/Prague
    restart: always
    depends_on:
      - db
    networks:
      default:
        aliases:
          - ca2
          - ejbca2
          - node2
  web:
    image: library/httpd:2.4
    container_name: ca_web
    hostname: ca-private
    environment:
      TZ: Europe/Prague
    volumes:
      - ./httpd_sav.conf:/usr/local/apache2/conf/httpd.conf
      - ./ssl:/etc/httpd/ssl
    restart: always
    depends_on:
      - ca1
      - ca2
    ports:
      - 8081:80
      - 443:443
    networks:
      default:
        aliases:
          - web
          - ca-private
