version: '2'
volumes:
  data:
    driver: local
  config:
    driver: local
  certs:
    driver: local

networks:
  default:
    driver: bridge

services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    domainname: "sysnet.cz"
    hostname: "ldap"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "SYSNET s.r.o."
      LDAP_DOMAIN: "sysnet.cz"
      LDAP_BASE_DN: "dc=sysnet,dc=cz"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #docker-compose.ymlLDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - data:/var/lib/ldap
      - config:/etc/ldap/slapd.d
      - certs:/container/service/slapd/assets/certs/
    ports:
      - "10389:389"
      - "10636:636"
    networks:
      default:
        aliases:
          - ldap
          - openldap
  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
    ports:
      - "8080:80"
    depends_on:
      - ldap
    networks:
      default:
        aliases:
          - ldapadmin
          - phpldapadmin