version: '3'
volumes:
  data:
    driver: local
  config:
    driver: local
  certs:
    driver: local

networks:
  default:
    driver: bridge

services:
  hydra-client:
    image: oryd/hydra:v1.4.10
    container_name: hydra-client
    environment:
      HYDRA_ADMIN_URL: http://hydra:4445
      LOG_LEVEL: trace
    command:
      - clients
      - create
      - --skip-tls-verify
      - --id
      - test-client
      - --secret
      - test-secret
      - --response-types
      - id_token,token,"id_token token"
      - --grant-types
      - implicit
      - --scope
      - openid,profile,email
      - --callbacks
      - http://localhost:3000
      - --post-logout-callbacks
      - http://localhost:3000/post-logout-callback
    networks:
      default:
        aliases:
          - hydra-client
    restart: always
    depends_on:
      - hydra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hydra:4445"]
      interval: 10s
      timeout: 10s
      retries: 10
  hydra:
    image: oryd/hydra:v1.4.10
    container_name: hydra
    environment:
      URLS_SELF_ISSUER: http://localhost:4444
      URLS_SELF_PUBLIC: http://localhost:4444
      URLS_LOGIN: http://localhost:8080/auth/login
      URLS_CONSENT: http://localhost:8080/auth/consent
      URLS_LOGOUT: http://localhost:8080/auth/logout
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPES: profile,email,phone
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_CLAIMS: name,family_name,given_name,nickname,email,phone_number
      DSN: memory
      LOG_LEVEL: trace
    command: serve all --dangerous-force-http
    networks:
      default:
        aliases:
          - hydra
          - oauth
    ports:
      - "4444:4444"
      - "4445:4445"
    restart: always
    depends_on:
      - werther
  werther:
    image: icoreru/werther
    container_name: werther
    environment:
      WERTHER_IDENTP_HYDRA_URL: http://hydra:4445
      WERTHER_LDAP_ENDPOINTS: ldap:389
      WERTHER_LDAP_BINDDN: cn=admin,dc=sysnet,dc=cz
      WERTHER_LDAP_BINDPW: admin
      WERTHER_LDAP_BASEDN: "dc=sysnet,dc=cz"
      WERTHER_LDAP_ROLE_BASEDN: "ou=AppRoles,dc=sysnet,dc=cz"
    networks:
      default:
        aliases:
          - werther
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - ldap
  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    domainname: "sysnet.cz"
    hostname: "ldap"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "SYSNET s.r.o."
      LDAP_DOMAIN: "sysnet.cz"
      LDAP_BASE_DN: "dc=sysnet,dc=cz"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #docker-compose.ymlLDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - data:/var/lib/ldap
      - config:/etc/ldap/slapd.d
      - certs:/container/service/slapd/assets/certs/
    ports:
      - "10389:389"
      - "10636:636"
    networks:
      default:
        aliases:
          - ldap
          - openldap
  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
    ports:
      - "8080:80"
    depends_on:
      - ldap
    networks:
      default:
        aliases:
          - ldapadmin
          - phpldapadmin