version: '3.1'

services:
  redmine:
    image: sysnetcz/redmine:3
    container_name: redmine
    depends_on:
      - db
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      MYSQL_PORT_3306_TCP: 'true'
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ${DB_PASSWORD}
      REDMINE_DB_DATABASE: redmine
    networks:
      default:
        aliases:
          - redmine
    volumes:
      - files:/usr/src/redmine/files
      - plugins:/usr/src/redmine/plugins
      - logs:/usr/src/redmine/log
      - ./configuration.yml:/usr/src/redmine/config/configuration.yml
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: redmine
    networks:
      default:
        aliases:
          - db
          - mysql
    volumes:
      - data:/var/lib/mysql
      - backup:/var/backups
  db-backup:       # https://github.com/databacker/mysql-backup
    image: databack/mysql-backup
    container_name: db-backup
    depends_on:
      - db
    restart: always
    volumes:
      - dump:/db
    environment:
      - TZ=Europe/Prague
      - DB_DUMP_TARGET=s3://${AWS_BUCKET}
      - DB_USER=root
      - DB_PASS=${DB_PASSWORD}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2330
      - DB_SERVER=db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    networks:
      default:
        aliases:
          - db-backup
          - backup
  file-backup:
    image: sysnetcz/s3sync
    container_name: file-backup
    depends_on:
      - redmine
    restart: always
    volumes:
      - files:/data:ro
    environment:
      - TZ=Europe/Prague
      - CRON_SCHEDULE=${S3_SYNC_CRON}
      - PARAMS=${S3_SYNC_PARAMS}
      - BUCKET=${AWS_BUCKET}
      - KEY=${AWS_ACCESS_KEY_ID}
      - SECRET=${AWS_SECRET_ACCESS_KEY}
      - REGION=${AWS_DEFAULT_REGION}
    networks:
      default:
        aliases:
          - file-backup
          - s3sync
  smtp:
    image: "catatnight/postfix"
    container_name: smtp
    restart: always
    ports:
      - "127.0.0.1:25:25"
    environment:
      - maildomain=sysnet.cz
      - smtp_user=redmine:${DB_PASSWORD}
    networks:
      default:
        aliases:
          - mail
          - smtp

volumes:
  files:
    driver: local
  plugins:
    driver: local
  data:
    driver: local
  logs:
    driver: local
  backup:
    driver: local
  dump:
    driver: local



networks:
  default:
    driver: bridge
