version: "3.5"
volumes:
  mq_data:
  mq_logs:

networks:
  maspd:
    driver: bridge
    name: maspd

services:
  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
#     - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - mq_data:/var/lib/rabbitmq/
      - mq_logs:/var/log/rabbitmq/
    environment:
#     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 127.0.0.1:15672:15672
    networks:
      maspd:
        aliases:
          - rabbitmq
          - mq
