heartbeat.monitors:
# vsechny hosty pomoci icmp ping
- type: icmp
  schedule: '@every 5s'
  #schedule: '*/5 * * * * * *'
  hosts:
    - sekm3-prod
    - sekm3-test
    - eap
    - mapserver
    - geoportal
    - apm
    - mysql
    - nginx
    - postgis
    - redis
  ipv4: true
  ipv6: false
  mode: any
  timeout: 3s
  wait: 1s

# Vsechny weby
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://controller:3011
    - http://portal:8000/portal
    - http://mapserver:80
    - http://geoportal:8081
    - http://nginx:80
  ipv4: true
  ipv6: false
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response:
    status: 200


# database
- type: tcp
  enabled: true
  schedule: '@every 5s'
  hosts:
    - tcp://mysql:3306
    - tcp://postgis:5432

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

xpack.monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true