version: '3'

networks:
  default:
    external:
      name: gis

volumes:
  lizmap-data:
    driver: local
  lizmap-log:
    driver: local
  wps-data:
    driver: local
  web-cache:
    driver: local
  web-log:
    driver: local

services:
  lizmap:
    image: 3liz/lizmap-web-client:${LIZMAP_VERSION_TAG}
    container_name: lizmap
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      APPDIR: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_USER_ID}
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_WPS_URL: http://wps:8080/
      LIZMAP_ADMIN_LOGIN: admin
      LIZMAP_ADMIN_EMAIL: admin@sysnetcz.com
      LIZMAP_ADMIN_DEFAILT_PASSWORD_SOURCE: /password
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - lizmap-data:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - lizmap-log:/www/lizmap/var/log
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/.password:/.password:ro
    command:
      - php-fpm
    restart: unless-stopped
  map:
    image: 3liz/qgis-map-server:${QGIS_VERSION_TAG}
    container_name: qgis-server
    environment:
      QGSRV_CACHE_SIZE: '20'
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_USER: ${LIZMAP_USER_ID}:${LIZMAP_USER_GID}
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_SERVER_WORKERS: ${QGIS_MAP_WORKERS}
      QGSRV_SERVER_PLUGINPATH: /srv/plugins
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGSPASSFILE: /srv/etc/pg_pass.conf
      QGIS_OPTIONS_PATH: /srv/etc/qgis
    volumes:
      - ${LIZMAP_DIR}/instances:/srv/projects
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/postgres/pg_service.conf:/srv/etc/pg_service.conf:ro
      - ${LIZMAP_DIR}/postgres/pg_pass.conf:/srv/etc/pg_pass.conf:ro
    - wps-data:/srv/data
    ports:
      - ${OWS_PORT}:8080
    restart: unless-stopped
  redis:
    image: redis:5-alpine
    container_name: redis
  web:
    image: nginx:1
    container_name: nginx
    user: ${LIZMAP_USER_ID}:${LIZMAP_USER_ID}
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - web-log:/var/log/nginx
      - web-cache:/var/cache/nginx
      - ${LIZMAP_DIR}:/srv/lizmap
    ports:
      - ${LIZMAP_PORT}:8080
    depends_on:
      - lizmap
