version: '3'
networks:
  graylog:
    # driver: bridge
    # name: graylog
    external:
      name: elk-dev_elastic

services:
  mongo:
    # image: mongo:4.2
    image: mongo:4
    container_name: mongo    
    networks:
      - graylog
  syslog:
    # image: graylog/graylog:4.0
    image: graylog/graylog:4.0
    container_name: syslog    
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=s3cr3tr00tpassw0rd
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
    ports:
      # Graylog web interface and REST API
      - 127.0.0.1:9000:9000
      # Syslog TCP
      - 127.0.0.1:1514:1514
      # Syslog UDP
      - 127.0.0.1:1514:1514/udp
      # GELF TCP
      - 127.0.0.1:12201:12201
      # GELF UDP
      - 127.0.0.1:12201:12201/udp
