version: "3"

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    expose: 
      - "8000"
      - "9000"
    ports:
      - "127:0:0:1:8000:8000"
      - "127.0.0.1:9000:9000"
    environment:
      - VIRTUAL_HOST=eap.sysnet.cz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    driver: local
